# Railway Build Configuration
[build]
  builder = "dockerfile"

[deploy]
  startCommand = "java -Dserver.port=$PORT -jar target/Cointoss-0.0.1-SNAPSHOT.jar"
  healthcheckPath = "/actuator/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10