spring:
  application:
    name: Cointoss
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  
  # datasource:
  #   url: ${DATABASE_URL}
  #   driver-class-name: org.postgresql.Driver
  #   hikari:
  #     maximum-pool-size: 5
  
  # jpa:
  #   hibernate:
  #     ddl-auto: validate
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQLDialect
  #       format_sql: true
  #   show-sql: false
  
  # flyway:
  #   enabled: false
  #   locations: classpath:db/migration
  #   baseline-on-migrate: true
  
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15 minutes
    refreshTokenExpiration: 604800 # 7 days
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: profile,email
            redirect-uri: ${FRONTEND_URL}/auth/callback/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

server:
  port: 8080
  forward-headers-strategy: framework

cors:
  allowed-origins: 
    - ${FRONTEND_URL:http://localhost:3000}
    - https://*.vercel.app
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this-in-production}
  expiration: 86400000

logging:
  level:
    com.example.cointoss: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# springdoc:
#   api-docs:
#     enabled: false
#   swagger-ui:
#     enabled: false